version: '3.3'

services:

  app:
    build: .
    container_name: finguard-app

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - mongo

    restart: always


  mongo:
    image: mongo

    container_name: finguard-mongo

    ports:
      - "27017:27017"

    restart: always

    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
