version: "3"

services:

  backend:

    build: .

    container_name: finguard-backend

    ports:
      - "5000:5000"

    environment:
      - MONGO_URI=mongodb://mongo:27017/finguard

    depends_on:
      - mongo

    restart: always


  frontend:

    build: ./frontend

    container_name: finguard-frontend

    ports:
      - "5173:5173"

    restart: always


  mongo:

    image: mongo

    container_name: finguard-mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

    restart: always


volumes:

  mongo-data: