FROM node:18-alpine AS base

WORKDIR /app

ENV NODE_ENV=production

FROM base AS deps
COPY package*.json ./
RUN npm ci --only=production

FROM base AS runner
COPY --from=deps /app/node_modules ./node_modules
COPY . .

EXPOSE 5000

USER node

CMD ["node", "server.js"]